### ISSUE TITLE
Delete server-side job on completion

### ISSUE THREAD

**Issue by NPavie** [daisy/pipeline-ui#139]
Since we are putting jobs on a more user-friendly folder, should we not delete the engine job when the results are transferred ?

**Comment by bertfrees** [comment]
If the job is deleted we can not get the log file anymore.

**Comment by marisademeglio** [comment]
maybe we should fetch the log file anyway and keep it in the same user-friendly folder as the job results (even if the job failed, the log file can be copied over), then it's easier to collect from users anyway, e.g. if they're filing a bug report, as it would be a standalone file instead of a web view.

**Comment by marisademeglio** [comment]
It works for me (tried now with DTBook Validator), which script did you run? I will try to reproduce.

**Comment by bertfrees** [comment]
Ok now it works, perhaps I was testing the wrong version earlier.

**Comment by bertfrees** [comment]
I was wondering: would it also be possible to open the detailed log in the browser, like it used to? For a lot of people the browser is more familiar than the program that has been set as the default for opening .log files. Currently the file opens in Console (macOS) for me. For other people it might be a text editor.
