### ISSUE TITLE
Add an "About DAISY Pipeline" panel

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#84]
It could contain:

- Version of Pipeline
- Address of the web server: host, port and path (`/ws`)

This would also allow simplifying the "Engine is running on port x" item in the tray menu to just "Engine is running". The about panel provides the same information and more. Users who need the information will know where to find it (and will be able to easily copy it from there), users that are not interested in this information are not bothered with it.

**Comment by ways2read** [comment]
Also consider adding information about DAISY (although it is quite long so consider a separate "About DAISY" panel:

The DAISY Consortium is the not-for-profit global authority on publishing and reading for people with blindness, low vision, and other print disabilities. Our members around the world have decades of experience producing accessible publications. Our team of international experts develops standards, tools, and best practices that are embraced by leading technology companies, publishers and library services.

Using the standards and tools developed by DAISY, our members and friends have produced millions of books, journals, newspapers and documents that can be read by people with disabilities in a way that works for them. Whether someone needs to read through enlarged text, audio, or braille, on whatever continent and in whatever language, there are technologies and standards developed by the DAISY Consortium that can make that information accessible to everyone, irrespective of disability. DAISY Consortium members and friends have made education and reading accessible to millions of people with disabilities, we invite you to join our mission!
daisy.org/join

**Comment by avneeshsingh** [comment]
One more thing:
On about page, I think you may have already thought of providing link to official pipeline webpage on daisy.org. It will also help people in discovering if there is a new release on the webpage.

**Comment by marisademeglio** [comment]
@avneeshsingh what is the official pipeline webpage URL that we would want for an About page? 

The candidates I have are:
- from @ways2read , [daisy.org/pipelineapphelp](https://daisy.org/pipelineapphelp), redirected to wherever we want; 
- or I could use [daisy.org/pipeline](https://daisy.org/pipeline), which seems like a good simple candidate, but that currently redirects to pipeline-1, and I don't know where all it's in use already. 
- Or I could instead use [daisy.org/activities/software/pipeline-2/](https://daisy.org/activities/software/pipeline-2/) but it feels a bit fragile as a link. 

The other links in the application menus are:
* "Learn more" goes to [DAISY Pipeline 2 on Github IO](https://daisy.github.io/pipeline/)
* "User guide" goes to [DAISY Pipeline 2, Getting Help on Github IO](https://daisy.github.io/pipeline/Get-Help/)

Are these links correct? 

I would expect a simpler structure overall, e.g. project homepage is at `daisy.org/pipeline` and the help entry point is `daisy.org/pipeline/help` (whether the contents ultimately lives on daisy.org or at github.io, we can have links that go out from that `/help` landing page).

I don't like the `/pipelineapphelp` fixed link that gets redirected because what about sub-pages, like above where I have `/pipeline` and also `/pipeline/help`. It feels too complicated to maintain a separate structure of "short" links.

**Comment by ways2read** [comment]
The entry point for the Pipeline project is daisy.org/pipeline<https://daisy.org/pipeline>. The Pipeline app will feature prominently and early on, but we also want to have information about the other Pipeline activities, including Pipeline 1 so that invested organisations don’t get the impression we’ve switched focus onto only the app.

From the app, I guess people will be looking for about and help related to the app, rather than the wider project. We could have daisy.org/pipelineapp<https://daisy.org/pipeline> as the short(ish) URL to give on slides for example. daisy.org/pipelineapphelp<https://daisy.org/pipeline> is a redirect to include in the code, I don’t know that humans would need to know it exists even.

Let’s try to avoid links in the menu going to the Github IO since this is information written for the developers and IT departments. Is Learn more going to the About information, and User guide going to the Information and Help pages? That feels right, but the way you wrote this they sound additional.

Richard

**Comment by bertfrees** [comment]
> Let’s try to avoid links in the menu going to the Github IO since this is information written for the developers and IT departments.

The difference between daisy.org and daisy.github.io is not that the former is for users and the latter for developers. The difference is that

- daisy.github.io contains all the documentation, daisy.org doesn't
- daisy.github.io was written _by_ developers
- we (the developer team) do not maintain daisy.org

We think (and have always said) that daisy.github.io should be integrated in daisy.org. It should be co-maintained by the communication, documentation and developer teams. It should be one and the same site, without HTTP redirects.

I agree that daisy.org/pipeline should be the entry point for the whole project including Pipeline 1.

**Comment by marisademeglio** [comment]
Here is an about box from [the about-box branch](https://github.com/daisy/pipeline-ui/tree/about-box). It might make it into this release? 

<img width="462" alt="Screenshot 2023-03-14 at 15 34 22" src="https://user-images.githubusercontent.com/734730/225157100-2e8fe4f8-e284-48a1-aeac-f97dc7803aa9.png">

**Comment by bertfrees** [comment]
Nice.
